name: task_project
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Localization and Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.7
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.4

  # Networking and Connectivity
  dio: ^5.9.2
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1

  # UI and Navigation
  shimmer: ^3.0.0
  go_router: ^17.1.0
  provider: ^6.1.5+1

  # Storage and Local Features
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2


  # Code Generation Support

  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.13

  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:

  assets:
    - assets/images/
    - assets/fonts/
    - assets/logo/
  uses-material-design: true
  fonts:
    - family: Overpass
      fonts:
        # Thin (100)
        - asset: assets/fonts/Overpass/static/Overpass-Thin.ttf
          weight: 100
        - asset: assets/fonts/Overpass/static/Overpass-ThinItalic.ttf
          weight: 100
          style: italic

        # ExtraLight (200)
        - asset: assets/fonts/Overpass/static/Overpass-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Overpass/static/Overpass-ExtraLightItalic.ttf
          weight: 200
          style: italic

        # Light (300)
        - asset: assets/fonts/Overpass/static/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/Overpass/static/Overpass-LightItalic.ttf
          weight: 300
          style: italic

        # Regular (400)
        - asset: assets/fonts/Overpass/static/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overpass/static/Overpass-Italic.ttf
          weight: 400
          style: italic

        # Medium (500)
        - asset: assets/fonts/Overpass/static/Overpass-Medium.ttf
          weight: 500
        - asset: assets/fonts/Overpass/static/Overpass-MediumItalic.ttf
          weight: 500
          style: italic

        # SemiBold (600)
        - asset: assets/fonts/Overpass/static/Overpass-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Overpass/static/Overpass-SemiBoldItalic.ttf
          weight: 600
          style: italic

        # Bold (700)
        - asset: assets/fonts/Overpass/static/Overpass-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overpass/static/Overpass-BoldItalic.ttf
          weight: 700
          style: italic

        # ExtraBold (800)
        - asset: assets/fonts/Overpass/static/Overpass-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Overpass/static/Overpass-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        # Black (900)
        - asset: assets/fonts/Overpass/static/Overpass-Black.ttf
          weight: 900



flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n
  output_dir: lib/src/common/l10n/generated

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/logo/weather_logo.png"
  image_path_ios: "assets/logo/weather_logo.png"
  adaptive_icon_background: "#07ACFC"

  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#07ACFC"


flutter_native_splash:
  color: "#07ACFC"
  image: "assets/logo/weather_logo.png"

  android_12:
    image: "assets/logo/weather_logo.png"
    color: "#07ACFC"

